### ISSUE TITLE
首頁檔案載入的速度

### ISSUE THREAD

**Issue by jungleft** [jungleft/picboard#23]
首頁檔案變多之後載入速度變慢，希望能順一點，目前想到載入順序文字>塗鴉>照片，
還是其實有更好的做法，想請問老師。

**Comment by bestian** [comment]
可以優先呈現文字，用setTimeout來延緩圖片和照片的呈現

也可以同步嘗試讓圖片和照片先呈現幾張，後面幾張之後再補上

**Comment by bestian** [comment]
另外從Fireabse讀取的時間是免不了的，可以放dimmer和loader來呈現"載入中..."3秒左右
